[project]
name = "crypto-dash"

[services.backend]
root = "crypto-dash-backend"
dockerfile = "Dockerfile"

[services.ai]
root = "crypto-dash-ai-backend"
dockerfile = "Dockerfile"

[services.frontend]
root = "crypto-dash-frontend"
dockerfile = "Dockerfile"
