[package]
name = "test_bybit_connection"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = { version = "0.21", features = ["native-tls"] }
futures = "0.3"
anyhow = "1.0"
serde_json = "1.0"
url = "2.4"

[[bin]]
name = "test_bybit_connection"
path = "test_bybit_connection.rs"